FROM python:alpine3.19
WORKDIR /app
COPY . /app
COPY requirements_fastApi.txt /usr/src/app/requirements_fastApi.txt
RUN pip install -r requirements_fastApi.txt
EXPOSE 6005

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "6005"]
#CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "6005", "--reload", "True"]

#uvicorn main:app --host 0.0.0.0 --port 5005